// packages/vue2/src/source/feedback/DataState.vue
<template>
  <div class="ds-data-state kjun-data-state" :aria-busy="loading || refreshing ? 'true' : 'false'">
    <!-- 갱신 표시의 바깥 DOM을 고정해 Vue 2의 본문 재사용·이동으로 인한 스크롤 초기화를 막는다. -->
    <div key="refresh-status">
      <div v-if="isRefreshing" class="ds-data-state-status kjun-data-status" role="status">
        <DsSpinner size="xs" /><span>{{ refreshingText }}</span>
      </div>
    </div>
    <!-- 첫 로딩: skeleton 모드 (재조회 시에는 hasLoadedOnce로 이전 콘텐츠 유지) -->
    <div v-if="isInitialLoading && skeleton" :class="loadingClasses" role="status" :aria-label="loadingText">
      <slot name="loading">
        <div class="space-y-3">
          <ds-skeleton
            v-for="i in skeletonCount"
            :key="i"
            :type="skeletonType"
          />
        </div>
      </slot>
    </div>

    <!-- 첫 로딩: 스피너 모드 (기본) -->
    <div v-else-if="isInitialLoading" :class="loadingClasses" role="status" :aria-label="loadingText">
      <slot name="loading">
        <div class="kjun-data-loading">
          <ds-spinner size="md" />
          <p>{{ loadingText }}</p>
        </div>
      </slot>
    </div>

    <!-- Error -->
    <div v-else-if="blockingError" class="kjun-state-actions" :class="containerClasses" :role="$scopedSlots.error || $slots.error ? 'alert' : undefined">
      <slot name="error" :error="error" :retry="emitRetry">
        <DsAlert type="danger" title="오류 발생">
          {{ error }}
          <template v-if="hasRetryListener" #actions>
            <DsButton variant="secondary" @click.stop="emitRetry">{{ retryText }}</DsButton>
          </template>
        </DsAlert>
      </slot>
    </div>

    <!-- Empty -->
    <div v-else-if="empty" class="kjun-data-empty kjun-state-actions" :class="containerClasses">
      <slot name="empty">
        <DsEmpty :text="emptyText" :icon="emptyIcon">
          <DsButton
            v-if="emptyActionText"
            @click.stop="$emit('empty-action')"
          >
            {{ emptyActionText }}
          </DsButton>
        </DsEmpty>
      </slot>
    </div>

    <!-- Content: 재조회 중에는 이전 콘텐츠를 유지한 채 dim 처리 (stale-while-revalidate) -->
    <div
      v-if="showContent"
      key="content"
      :class="{
        'ds-data-state-refreshing': loading && !usesQueryState,
        'ds-data-state-concealed': contentConcealed,
      }"
      :aria-hidden="contentConcealed ? 'true' : undefined"
      :inert="contentConcealed ? '' : null"
    >
      <slot></slot>
    </div>
    <div v-if="visibleRefreshError && !isInitialLoading" class="kjun-data-warning kjun-state-actions">
    <!-- Retry sits in the actions slot like the blocking error; the sm alert sizes the button. -->
    <DsAlert type="warning" size="sm">
      {{ visibleRefreshError }} · 이전 조회 결과를 표시하고 있습니다.
      <template v-if="hasRetryListener" #actions>
        <DsButton variant="secondary" @click.stop="emitRetry">{{ retryText }}</DsButton>
      </template>
    </DsAlert>
    </div>
  </div>
</template>

<script>
import DsAlert from "./Alert.vue";
import DsButton from "../primitives/Button.vue";
import DsEmpty from "../data-display/Empty.vue";
import DsSkeleton from "../data-display/Skeleton.vue";
import DsSpinner from "./Spinner.vue";
import { componentMixins } from "../../component-mixins.js";
import queryDisplayMixin from '@kjun-adapter/queryDisplayMixin.js'

export default {
  components: { DsAlert, DsButton, DsEmpty, DsSkeleton, DsSpinner },
  name: 'DsDataState',
  mixins: [queryDisplayMixin, ...componentMixins],
  props: {
    // null은 기존 계약을 유지한다. 조건 키를 전달한 화면만 동일 조건 갱신에서 본문을 보존한다.
    queryKey: { type: [String, Number], default: null },
    // 차트·표 인스턴스가 있는 영역은 조건 변경 중에도 기존 DOM을 보존한다.
    preserveContent: { type: Boolean, default: false },
    refreshing: { type: Boolean, default: false },
    refreshError: { type: String, default: null },
    refreshingText: { type: String, default: '갱신 중...' },
    loadingPadding: {
      type: String,
      default: 'default',
      validator: value => ['default', 'none'].includes(value),
    },
    loading: {
      type: Boolean,
      default: false
    },
    // true면 재조회 시 스피너로 교체하지 않고 이전 콘텐츠를 유지한다 (첫 로딩만 스피너/스켈레톤)
    hasLoadedOnce: {
      type: Boolean,
      default: false
    },
    error: {
      type: String,
      default: null
    },
    empty: {
      type: Boolean,
      default: false
    },
    emptyText: {
      type: String,
      default: '데이터가 없습니다'
    },
    // 기본은 텍스트만 — 빈 상태 아이콘은 필요한 페이지에서 empty-icon으로 명시 opt-in (DsEmpty와 동일 규칙)
    emptyIcon: {
      type: String,
      default: ''
    },
    emptyActionText: {
      type: String,
      default: null
    },
    loadingText: {
      type: String,
      default: '로딩 중...'
    },
    retryText: {
      type: String,
      default: '다시 시도'
    },
    size: {
      type: String,
      default: 'md',
      validator: (v) => ['sm', 'md', 'lg'].includes(v)
    },
    skeleton: {
      type: Boolean,
      default: false,
    },
    skeletonType: {
      type: String,
      default: 'text',
      validator: (v) => ['text', 'card', 'table', 'stat', 'chart', 'block'].includes(v),
    },
    skeletonCount: {
      type: Number,
      default: 3,
    }
  },
  computed: {
    contentConcealed() { return this.isInitialLoading || !!this.blockingError || this.empty },
    showContent() { return !this.contentConcealed || (this.preserveContent && this.hasQueryResult) },
    isInitialLoading() {
      return this.loading && !this.hasCurrentResult
    },
    isRefreshing() { return this.refreshing || (this.usesQueryState && this.loading && this.hasCurrentResult) },
    blockingError() { return this.error && !(this.usesQueryState && this.hasCurrentResult) },
    visibleRefreshError() {
      return this.refreshError || (this.usesQueryState && this.hasCurrentResult ? this.error : null)
    },
    loadingClasses() { return this.loadingPadding === 'none' ? '' : this.containerClasses },
    containerClasses() {
      const sizes = {
        sm: 'py-state-padding-sm',
        md: 'py-state-padding-md',
        lg: 'py-state-padding-lg'
      }
      return sizes[this.size]
    },
    hasRetryListener() {
      return !!(this.$listeners && this.$listeners.retry)
    }
  },
  methods: {
    emitRetry() {
      this.$emit('retry')
    }
  }
}
</script>

<style scoped>
.ds-data-state { position: relative; }
.ds-data-state-concealed { position: absolute; top: 0; left: 0; right: 0; visibility: hidden; pointer-events: none; }
.ds-data-state-refreshing {
  opacity: var(--_kjun-state-opacity-pending);
  pointer-events: none;
  transition: opacity var(--motion-control) var(--ease-out);
}
</style>

// packages/native/src/data-state.tsx
import { typeStyle } from "./typography";
import {
tokens,
advanceQueryDisplay,
initialQueryDisplay,
queryDisplayStatus,
type QueryDisplayProps,
} from "@kjun/tokens";
import { Component,useState,type ErrorInfo,type ReactNode } from "react";
import { Platform,View,type ViewStyle } from "react-native";
import { DataStateContentContext } from "./data-state-context";
import { DsButton } from "./button";
import {
DsAlert,
DsEmpty,
DsSkeleton,
DsSpinner,
type DsSkeletonProps,
} from "./display";
import { KText,content } from "./internal";
import { useKjunStyles } from "./provider";
export function useQueryDisplay(props: QueryDisplayProps) {
  const [state, setState] = useState(() => initialQueryDisplay(props));
  let next = state;
  if (
    state.queryKey !== (props.queryKey ?? null) ||
    state.resultKey !== props.resultKey ||
    state.loading !== !!props.loading
  ) {
    next = advanceQueryDisplay(state, props);
    setState(next);
  }
  return queryDisplayStatus(next, props);
}
export interface DsDataStateProps extends QueryDisplayProps {
  preserveContent?: boolean;
  refreshing?: boolean;
  refreshError?: string | null;
  refreshingText?: string;
  loadingPadding?: "default" | "none";
  empty?: boolean;
  emptyText?: string;
  emptyIcon?: string;
  emptyActionText?: string;
  loadingText?: string;
  retryText?: string;
  size?: "sm" | "md" | "lg";
  skeleton?: boolean;
  skeletonType?: DsSkeletonProps["type"];
  skeletonCount?: number;
  children?: ReactNode;
  loadingContent?: ReactNode;
  emptyContent?: ReactNode;
  errorContent?: ReactNode;
  onRetry?: () => void;
  onEmptyAction?: () => void;
}
export function DsDataState({
  preserveContent = false,
  refreshing = false,
  refreshError,
  refreshingText = "갱신 중...",
  loadingPadding = "default",
  empty = false,
  emptyText = "데이터가 없습니다",
  emptyIcon,
  emptyActionText,
  loadingText = "로딩 중...",
  retryText = "다시 시도",
  size = "md",
  skeleton = false,
  skeletonType = "text",
  skeletonCount = 3,
  children,
  loadingContent,
  emptyContent,
  errorContent,
  onRetry,
  onEmptyAction,
  ...query
}: DsDataStateProps) {
  const state = useQueryDisplay(query),
    blockingError =
      query.error && !(state.usesQueryState && state.hasCurrentResult),
    visibleRefreshError =
      refreshError ||
      (state.usesQueryState && state.hasCurrentResult ? query.error : null),
    concealed = state.initialLoading || !!blockingError || empty,
    padding = tokens.extensions.state.padding[size];
  const { colors } = useKjunStyles();
  return (
    <View
      style={{ position: "relative" }}
      accessibilityState={{ busy: !!query.loading || refreshing }}
    >
      <View>
        {(refreshing || state.queryRefreshing) && (
          <View
            accessibilityRole="alert"
            style={{
              alignSelf: "flex-end",
              maxWidth: "100%",
              marginBottom: tokens.dimension.value12,
              flexDirection: "row",
              alignItems: "center",
              gap: tokens.dimension.value6,
              paddingVertical: tokens.dimension.value4,
              paddingHorizontal: tokens.dimension.value8,
              borderRadius: tokens.radius.radius12,
              backgroundColor: colors.surface,
            }}
          >
            <DsSpinner size="xs" />
            <KText style={{ ...typeStyle('caption'), color: colors.textTertiary, flexShrink: 1, minWidth: 0 }}>
              {refreshingText}
            </KText>
          </View>
        )}
      </View>
      {state.initialLoading ? (
        <View
          accessibilityLabel={loadingText}
          style={{ paddingVertical: loadingPadding === "none" ? 0 : padding }}
        >
          {loadingContent ||
            (skeleton ? (
              <View style={{ gap: tokens.dimension.value12 }}>
                {Array.from({ length: skeletonCount }, (_, i) => (
                  <DsSkeleton key={i} type={skeletonType} />
                ))}
              </View>
            ) : (
              <View style={{ alignItems: "center", gap: tokens.dimension.value12 }}>
                <DsSpinner size="md" />
                <KText style={{ ...typeStyle("body"), color: colors.textSecondary, textAlign: "center", maxWidth: "100%" }}>{loadingText}</KText>
              </View>
            ))}
        </View>
      ) : blockingError ? (
        <DataStateContentContext.Provider value="message">
        <View style={{ paddingVertical: padding }}>
          {errorContent || (
            <DsAlert type="danger" title="오류 발생" actions={onRetry && (
              <DsButton variant="secondary" onPress={onRetry}>
                {retryText}
              </DsButton>
            )}>
              {/* The alert's own body type applies, like any other DsAlert. */}
              {query.error}
            </DsAlert>
          )}
        </View>
        </DataStateContentContext.Provider>
      ) : empty ? (
        <DataStateContentContext.Provider value="empty">
        <View style={{ paddingVertical: padding }}>
          {emptyContent || (
            <DsEmpty text={emptyText} icon={emptyIcon}>
              {emptyActionText && (
                <DsButton onPress={onEmptyAction}>{emptyActionText}</DsButton>
              )}
            </DsEmpty>
          )}
        </View>
        </DataStateContentContext.Provider>
      ) : null}
      {(!concealed || (preserveContent && state.hasQueryResult)) && (
        <View
          key="content"
          accessibilityElementsHidden={concealed}
          importantForAccessibility={concealed ? "no-hide-descendants" : "auto"}
          pointerEvents={concealed ? "none" : "auto"}
          style={
            concealed
              ? {
                  position: "absolute",
                  top: 0,
                  left: 0,
                  right: 0,
                  opacity: 0,
                  ...(Platform.OS === "web"
                    ? ({ visibility: "hidden" } as ViewStyle)
                    : {}),
                }
              : { opacity: query.loading && !state.usesQueryState ? tokens.states.opacity.pending : 1 }
          }
        >
          {content(children)}
        </View>
      )}
      {visibleRefreshError && !state.initialLoading && (
        <DataStateContentContext.Provider value="message">
        <View style={{ marginTop: tokens.dimension.value12 }}>
        {/* Retry sits in the actions slot like the blocking error; the sm alert sizes the button. */}
        <DsAlert type="warning" size="sm" actions={onRetry && (
          <DsButton variant="secondary" onPress={onRetry}>
            {retryText}
          </DsButton>
        )}>
          {`${visibleRefreshError} · 이전 조회 결과를 표시하고 있습니다.`}
        </DsAlert>
        </View>
        </DataStateContentContext.Provider>
      )}
    </View>
  );
}
function BoundaryDescription() {
  const { colors } = useKjunStyles();
  return <KText style={{ ...typeStyle({ ...tokens.typography.caption, fontSizePx: tokens.extensions.state.descriptionSize }), color:colors.textSecondary, textAlign:"center" }}>다시 시도하면 문제가 해결될 수 있습니다.</KText>;
}
export interface DsErrorBoundaryProps {
  children: ReactNode;
  fallbackMessage?: string;
  fallback?: ReactNode;
  onError?: (error: Error, info: ErrorInfo) => void;
  onReset?: () => void;
}
export class DsErrorBoundary extends Component<
  DsErrorBoundaryProps,
  { error: boolean }
> {
  state = { error: false };
  static getDerivedStateFromError() {
    return { error: true };
  }
  componentDidCatch(error: Error, info: ErrorInfo) {
    this.props.onError?.(error, info);
  }
  render() {
    return this.state.error
      ? this.props.fallback || (
          <View
            style={{
              alignItems: "center",
              paddingVertical: tokens.dimension.value64,
              paddingHorizontal: tokens.dimension.value24,
              gap: tokens.dimension.value16,
            }}
          >
            <View style={{ gap:tokens.dimension.value8, alignItems:"center" }}>
            <KText style={{ ...typeStyle({ ...tokens.typography.sectionTitle, fontSizePx: tokens.extensions.state.titleSize }), textAlign:"center" }}>
              {this.props.fallbackMessage || "문제가 발생했습니다"}
            </KText>
            <BoundaryDescription />
            </View>
            {/* DsButton hugs the start edge by default; the fallback centers it with its text.
                It resets the boundary rather than reloading the page, like DataState's retry. */}
            <DsButton
              style={{ alignSelf: "center" }}
              onPress={() => {
                this.setState({ error: false });
                this.props.onReset?.();
              }}
            >
              다시 시도
            </DsButton>
          </View>
        )
      : this.props.children;
  }
}
